apiVersion: v1
kind: Package
metadata:
  name: rabbitmq-helm-chart
  version: 0.1.0
  description: A Helm chart for deploying rabbitmq on Kubernetes.
  keywords:
    - rabbitmq
    - helm
  maintainers:
    - name: Sohan
      email: sohanyadavdevops@gmail.com
  sources:
    - name: GitHub
      url: https://github.com/cypik-view/rabbitmq-helm-chart
  home: https://github.com/cypik-view/rabbitmq-helm-chart
