apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.amqpPort }}
            - containerPort: {{ .Values.service.managementPort }}
            - containerPort: {{ .Values.service.stompPort }}
          env:
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
            - name: RABBITMQ_LOAD_DEFINITIONS
              value: "/etc/rabbitmq/definitions.json"
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "check_port_connectivity"]
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: shared-storage
              mountPath: /var/lib/rabbitmq
              subPath: .data
            - name: shared-storage
              mountPath: /var/log/rabbitmq
              subPath: .logs
            - name: config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
            - name: plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
            - name: definitions
              mountPath: /etc/rabbitmq/definitions.json
              subPath: definitions.json

      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc-claim
        - name: config
          configMap:
            name: rabbitmq-config
            items:
              - key: rabbitmq.conf
                path: rabbitmq.conf
        - name: plugins
          configMap:
            name: plugins-config
            items:
              - key: enabled-plugins
                path: enabled_plugins
        - name: definitions
          configMap:
            name: definitions-config
            items:
              - key: definitions.json
                path: definitions.json
