apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.service.amqpPort }}
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
    - name: stomp
      port: {{ .Values.service.stompPort }}
      targetPort: {{ .Values.service.stompPort }}
